# Generated by Django 5.1.2 on 2024-10-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_discription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
