# Generated by Django 5.1.2 on 2024-10-30 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0002_program_program_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Document.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='programs',
            field=models.ManyToManyField(blank=True, to='Document.program'),
        ),
    ]
