# Generated by Django 5.1.2 on 2024-10-30 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0003_remove_student_program_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instructor_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='student',
            name='programs',
        ),
        migrations.AddField(
            model_name='student',
            name='programs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Document.program'),
        ),
    ]
