# Generated by Django 5.1.2 on 2024-11-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0004_alter_department_department_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='logo_path',
            field=models.ImageField(blank=True, null=True, upload_to='university_logos/'),
        ),
    ]
