# Generated by Django 5.1.2 on 2025-05-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0005_alter_university_logo_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='temp_id',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='type',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='department',
            name='programs',
        ),
    ]
