# Generated by Django 5.1.2 on 2025-05-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0006_rename_temp_id_template_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
