# Generated by Django 5.1.2 on 2025-05-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0007_alter_program_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
