# Generated by Django 5.1.2 on 2025-05-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0009_alter_department_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='logo_path',
        ),
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='university_logos/'),
        ),
    ]
