# Generated by Django 5.1.2 on 2025-05-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0010_remove_university_logo_path_university_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='university_code',
            new_name='code',
        ),
    ]
