# Generated by Django 5.1.2 on 2025-05-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0012_alter_university_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_code',
            new_name='code',
        ),
    ]
