services:
  - type: web
    name: smart-dms
    env: python
    buildCommand: |
      cd Smart_Document
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: |
      cd Smart_Document
      gunicorn Smart_Document.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your_secret_key_here
      - key: DEBUG
        value: False
